apiVersion: v1
kind: ConfigMap
metadata:
  name: district-badges-config
  namespace: district-badges
data:
  APP_FULL_BASE_URL: https://badges.lbdscouts.org.uk
  DEBUG: "false"
  ALGOLIA_INDEX_BADGES: BADGES
