apiVersion: v1
kind: ConfigMap
metadata:
  name: district-badges-config
  namespace: district-badges
data:
  APP_NAME: district-badges
  APP_ENCODING: UTF-8
  APP_DEFAULT_LOCALE: en_GB
  APP_DEFAULT_TIMEZONE: Europe/London
  APP_FULL_BASE_URL: https://badges.example.com
  AWS_REGION: eu-west-1
  DEBUG: "false"
  EMAIL_FROM_ADDRESS: orders@badges-dev.lbdscouts.org.uk
  EMAIL_FROM_NAME: LBA Scouts District Badge Shop (Development)
  ORDER_NOTIFICATIONS_ENABLED: "true"
  ALGOLIA_ENABLED: "true"
  ALGOLIA_INDEX_BADGES: BADGES-DEV
