approvedGitRepositories:
  - "**"

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

npmScopes:
  lbdistrictscouts:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.pkg.github.com"
