apiVersion: v1
kind: Service
metadata:
  name: district-badges-web
  namespace: district-badges
spec:
  type: LoadBalancer
  selector:
    app: district-badges
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https
